export const projects = [
  {
    id: 1,
    projectName: "R8tr App",
    startDate: "12-8-2021",
    endDate: "12-10-2023",
    status: "Completed",
    projectTech: ["React JS", "Redux", "Mui", "Socket", "Firebase"],
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus esse commodi deserunt vitae, vero quasi! Veniam quaerat tenetur pariatur doloribus.",
    createdAt: "2023-11-07T06:08:49.000Z",
    updatedAt: "2023-11-07T06:08:49.000Z",
    userName: "arslan_qadir",
    Media: {
      id: 2,
      projectImages: [
        { src: "/images/r8tr/login.webp" },
        { src: "/images/r8tr/r8tr-login.webp" },
        { src: "/images/r8tr/r8tr-dashboard.webp" },
        { src: "/images/r8tr/r8tr-info.webp" },
        { src: "/images/r8tr/r8tr-expertise.webp" },
        { src: "/images/r8tr/job-detail.webp" },
        { src: "/images/r8tr/rating-step.webp" },
        { src: "/images/r8tr/buyer-dashborad.webp" },
        { src: "/images/r8tr/Hire-R8tr.webp" },
        { src: "/images/r8tr/payment-info.webp" },
        { src: "/images/r8tr/resent-card.webp" },
        { src: "/images/r8tr/buyer-rating-step.webp" },
        { src: "/images/r8tr/Hire-R8tr-two.webp" },
      ],
      createdAt: "2023-11-07T06:48:56.000Z",
      updatedAt: "2023-11-07T06:48:56.000Z",
      projectId: 1,
    },
    Video: {
      id: 5,
      projectVideo: "project-video-1.mp4",
      projectId: 1,
      createdAt: "2023-11-21T05:23:37.000Z",
      updatedAt: "2023-11-21T05:23:37.000Z",
    },
  },
  {
    id: 3,
    projectName: "Workbay Pro",
    startDate: "12-8-2021",
    endDate: "12-10-2023",
    status: "Completed",
    projectTech: ["React JS", "Redux", "Mui", "Socket", "Firebase"],
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus esse commodi deserunt vitae, vero quasi! Veniam quaerat tenetur pariatur doloribus.",
    createdAt: "2023-11-07T06:08:49.000Z",
    updatedAt: "2023-11-07T06:08:49.000Z",
    userName: "arslan_qadir",
    Media: {
      id: 3,
      projectImages: [
        { src: "/images/workbay-pro/login.png" },
        { src: "/images/workbay-pro/workbay-Dashboard.jpg" },
        { src: "/images/workbay-pro/workbay-Dashboard.jpg" },
        { src: "/images/workbay-pro/Workflow.jpg" },
        { src: "/images/workbay-pro/Dashboard-two.png" },
        { src: "/images/workbay-pro/edit-card.png" },
        { src: "/images/workbay-pro/request-form.png" },
      ],
      createdAt: "2023-11-07T06:48:56.000Z",
      updatedAt: "2023-11-07T06:48:56.000Z",
      projectId: 1,
    },
    Video: {
      id: 5,
      projectVideo: "project-video-1.mp4",
      projectId: 1,
      createdAt: "2023-11-21T05:23:37.000Z",
      updatedAt: "2023-11-21T05:23:37.000Z",
    },
  },
  {
    id: 2,
    projectName: "Kepler Vision",
    startDate: "12-8-2021",
    endDate: "12-10-2023",
    status: "Completed",
    projectTech: ["React JS", "Redux", "Mui", "Socket", "Firebase"],
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus esse commodi deserunt vitae, vero quasi! Veniam quaerat tenetur pariatur doloribus.",
    createdAt: "2023-11-07T06:08:49.000Z",
    updatedAt: "2023-11-07T06:08:49.000Z",
    userName: "arslan_qadir",
    Media: {
      id: 3,
      projectImages: [
        { src: "/images/kepler/kepler-login.jpg" },
        { src: "/images/kepler/kepler-Dashboard.jpg" },
        { src: "/images/kepler/kepler-Dashboard-two.jpg" },
        { src: "/images/kepler/Client-Detail.jpg" },
        { src: "/images/kepler/Add-Location.jpg" },
        { src: "/images/kepler/Connect-Appliance.jpg" },
        { src: "/images/kepler/Client-Detail-2.jpg" },
        { src: "/images/kepler/Connect-Stream.jpg" },
        { src: "/images/kepler/Connect-Stream-list.jpg" },
        { src: "/images/kepler/Edit-Stream.jpg" },
        { src: "/images/kepler/Succesfully-connected.jpg" },
      ],
      createdAt: "2023-11-07T06:48:56.000Z",
      updatedAt: "2023-11-07T06:48:56.000Z",
      projectId: 1,
    },
    Video: {
      id: 5,
      projectVideo: "project-video-1.mp4",
      projectId: 1,
      createdAt: "2023-11-21T05:23:37.000Z",
      updatedAt: "2023-11-21T05:23:37.000Z",
    },
  },
  {
    id: 2,
    projectName: "R8tr Portal",
    startDate: "12-8-2021",
    endDate: "12-10-2023",
    status: "Completed",
    projectTech: ["React JS", "Redux", "Mui", "Socket", "Firebase"],
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus esse commodi deserunt vitae, vero quasi! Veniam quaerat tenetur pariatur doloribus.",
    createdAt: "2023-11-07T06:08:49.000Z",
    updatedAt: "2023-11-07T06:08:49.000Z",
    userName: "arslan_qadir",
    Media: {
      id: 3,
      projectImages: [
        { src: "/images/r8tr-admin/admin-login.png" },
        { src: "/images/r8tr-admin/Dashboard.webp" },
        { src: "/images/r8tr-admin/jobs.webp" },
        { src: "/images/r8tr-admin/jobs.webp" },
        { src: "/images/r8tr-admin/jobs-details.webp" },
        { src: "/images/r8tr-admin/stats.webp" },
        { src: "/images/r8tr-admin/categories.webp" },
        { src: "/images/r8tr-admin/costs.webp" },
        { src: "/images/r8tr-admin/costs-details.webp" },
        { src: "/images/r8tr-admin/Damages.webp" },
        { src: "/images/r8tr-admin/discount.webp" },
      ],
      createdAt: "2023-11-07T06:48:56.000Z",
      updatedAt: "2023-11-07T06:48:56.000Z",
      projectId: 1,
    },
    Video: {
      id: 5,
      projectVideo: "project-video-1.mp4",
      projectId: 1,
      createdAt: "2023-11-21T05:23:37.000Z",
      updatedAt: "2023-11-21T05:23:37.000Z",
    },
  },
  {
    id: 4,
    projectName: "Template",
    startDate: "12-8-2021",
    endDate: "12-10-2023",
    status: "Completed",
    projectTech: ["React JS", "Redux", "Mui", "Socket", "Firebase"],
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus esse commodi deserunt vitae, vero quasi! Veniam quaerat tenetur pariatur doloribus.",
    createdAt: "2023-11-07T06:08:49.000Z",
    updatedAt: "2023-11-07T06:08:49.000Z",
    userName: "arslan_qadir",
    Media: {
      id: 4,
      projectImages: [
        { src: "/images/template/part-1.bmp" },
        { src: "/images/template/part-2.bmp" },
        { src: "/images/template/part-3.bmp" },
        { src: "/images/template/part-4.bmp" },
        { src: "/images/template/part-5.bmp" },
        { src: "/images/template/part-6.bmp" },
      ],
      createdAt: "2023-11-07T06:48:56.000Z",
      updatedAt: "2023-11-07T06:48:56.000Z",
      projectId: 1,
    },
    Video: {
      id: 5,
      projectVideo: "project-video-1.mp4",
      projectId: 1,
      createdAt: "2023-11-21T05:23:37.000Z",
      updatedAt: "2023-11-21T05:23:37.000Z",
    },
  },
];
