export const projects = [
  {
    id: 1,
    projectName: "R8tr App",
    startDate: "12-8-2023",
    endDate: "22-10-2023",
    status: "Completed",
    projectTech: ["React JS", "Redux", "Mui", "Socket", "Firebase"],
    projectDescription:
      "project is a car inspection platform with two user roles:buyers and r8trs. Buyers can create inspection jobs,providing vehicle details and making payments through Braintree. R8trs sign up,complete profiles with expertise levels, areas of expertise, and service areas.R8trs view nearby jobs on a map, accept or cancel them, and rate vehicles upon acceptance. They complete job criteria, uploading images and videos.Buyers can view completed jobs, ratings, download PDF reports, and both users can communicate with admin via a chat system. The platform facilitates efficient car inspections and communication between buyers, r8trs, and the admin.",
    createdAt: "2023-11-07T06:08:49.000Z",
    updatedAt: "2023-11-07T06:08:49.000Z",
    userName: "arslan_qadir",
    Media: {
      id: 2,
      projectImages: [
        { src: "/images/r8tr/login.webp" },
        { src: "/images/r8tr/r8tr-login.webp" },
        { src: "/images/r8tr/r8tr-dashboard.webp" },
        { src: "/images/r8tr/r8tr-info.webp" },
        { src: "/images/r8tr/r8tr-expertise.webp" },
        { src: "/images/r8tr/job-detail.webp" },
        { src: "/images/r8tr/rating-step.webp" },
        { src: "/images/r8tr/buyer-dashborad.webp" },
        { src: "/images/r8tr/Hire-R8tr.webp" },
        { src: "/images/r8tr/payment-info.webp" },
        { src: "/images/r8tr/resent-card.webp" },
        { src: "/images/r8tr/buyer-rating-step.webp" },
        { src: "/images/r8tr/Hire-R8tr-two.webp" },
      ],
      createdAt: "2023-11-07T06:48:56.000Z",
      updatedAt: "2023-11-07T06:48:56.000Z",
      projectId: 1,
    },
    Video: {
      id: 5,
      projectVideo: "project-video-1.mp4",
      projectId: 1,
      createdAt: "2023-11-21T05:23:37.000Z",
      updatedAt: "2023-11-21T05:23:37.000Z",
    },
  },
  {
    id: 3,
    projectName: "Workbay Pro",
    startDate: "12-8-2021",
    endDate: "12-5-2023",
    status: "Completed",
    projectTech: ["React JS", "Redux", "Mui", "Socket", "Firebase"],
    projectDescription:
      "This project involves the development of an online platform called Workday-Pro for shopkeepers to create their own virtual stores. Shopkeepers can share their store application form links on various online platforms or independently generate requests. Clients, upon accessing the link, provide their vehicle information and details about any issues. The shopkeeper receives a notification of the request and can access comprehensive information about the vehicle model using a motor API, including mileage and recommended part replacements.If any parts need replacement, the shopkeeper checks the integrated online platform for spare parts. Once all necessary information is added, the shopkeeper sends a request back to the client for approval. If the client approves, the shopkeeper confirms the spare part order and proceeds to assign the job to a technician. The system allows for tracking the technician's performance throughout the process.",
    createdAt: "2023-11-07T06:08:49.000Z",
    updatedAt: "2023-11-07T06:08:49.000Z",
    userName: "arslan_qadir",
    Media: {
      id: 3,
      projectImages: [
        { src: "/images/workbay-pro/login.png" },
        { src: "/images/workbay-pro/workbay-Dashboard.jpg" },
        { src: "/images/workbay-pro/workbay-Dashboard.jpg" },
        { src: "/images/workbay-pro/Workflow.jpg" },
        { src: "/images/workbay-pro/Dashboard-two.png" },
        { src: "/images/workbay-pro/edit-card.png" },
        { src: "/images/workbay-pro/request-form.png" },
      ],
      createdAt: "2023-11-07T06:48:56.000Z",
      updatedAt: "2023-11-07T06:48:56.000Z",
      projectId: 1,
    },
    Video: {
      id: 5,
      projectVideo: "project-video-1.mp4",
      projectId: 1,
      createdAt: "2023-11-21T05:23:37.000Z",
      updatedAt: "2023-11-21T05:23:37.000Z",
    },
  },
  {
    id: 3,
    projectName: "Kepler Vision",
    startDate: "12-8-2021",
    endDate: "12-10-2023",
    status: "Completed",
    projectTech: ["React JS", "Redux-toolkit", "Mui", "Socket", "Firebase"],
    projectDescription:
      "The Kepler Vision Portal project is a user-friendly platform designed for administrators and users. Utilizing Okta for secure login, users are directed to a dashboard where administrators can conveniently view a list of appliances and users. The admin has the capability to add new appliances, locations, and streams. Notably, the system supports bulk stream uploads through CSV files, enabling efficient data management. Additionally, the portal facilitates data editing and provides instant feedback by notifying administrators if any required information is missing during the process.",
    createdAt: "2023-11-07T06:08:49.000Z",
    updatedAt: "2023-11-07T06:08:49.000Z",
    userName: "arslan_qadir",
    Media: {
      id: 3,
      projectImages: [
        { src: "/images/kepler/kepler-login.jpg" },
        { src: "/images/kepler/kepler-Dashboard.jpg" },
        { src: "/images/kepler/kepler-Dashboard-two.jpg" },
        { src: "/images/kepler/Client-Detail.jpg" },
        { src: "/images/kepler/Add-Location.jpg" },
        { src: "/images/kepler/Connect-Appliance.jpg" },
        { src: "/images/kepler/Client-Detail-2.jpg" },
        { src: "/images/kepler/Connect-Stream.jpg" },
        { src: "/images/kepler/Connect-Stream-list.jpg" },
        { src: "/images/kepler/Edit-Stream.jpg" },
        { src: "/images/kepler/Succesfully-connected.jpg" },
      ],
      createdAt: "2023-11-07T06:48:56.000Z",
      updatedAt: "2023-11-07T06:48:56.000Z",
      projectId: 1,
    },
    Video: {
      id: 5,
      projectVideo: "project-video-1.mp4",
      projectId: 1,
      createdAt: "2023-11-21T05:23:37.000Z",
      updatedAt: "2023-11-21T05:23:37.000Z",
    },
  },
  {
    id: 4,
    projectName: "R8tr Portal",
    startDate: "12-9-2022",
    endDate: "12-11-2023",
    status: "Completed",
    projectTech: ["React JS", "Redux", "Mui", "Socket", "Firebase"],
    projectDescription:
      "The admin portal of R8tr Web manages multiple user roles,including super admin, admin, and manager. Each user has access to specific routes based on permissions granted by the super admin. Admins can view R8tr lists on a map and table, send notifications to individual or multiple R8trs, and manage job lists. They have the ability to view detailed ratings for each job, create jobs individually or in bulk through CSV uploads, and download PDFs of rating details.Admins can also update vehicle categories, add or modify criteria within categories, create discounts, and generate coupons for users. Additionally, they have the authority to set permissions for different roles within the portal. A notable feature is the chat system, allowing admins to communicate with any user directly through the platform.",
    createdAt: "2023-11-07T06:08:49.000Z",
    updatedAt: "2023-11-07T06:08:49.000Z",
    userName: "arslan_qadir",
    Media: {
      id: 3,
      projectImages: [
        { src: "/images/r8tr-admin/admin-login.png" },
        { src: "/images/r8tr-admin/Dashboard.webp" },
        { src: "/images/r8tr-admin/jobs.webp" },
        { src: "/images/r8tr-admin/jobs.webp" },
        { src: "/images/r8tr-admin/jobs-details.webp" },
        { src: "/images/r8tr-admin/stats.webp" },
        { src: "/images/r8tr-admin/categories.webp" },
        { src: "/images/r8tr-admin/costs.webp" },
        { src: "/images/r8tr-admin/costs-details.webp" },
        { src: "/images/r8tr-admin/Damages.webp" },
        { src: "/images/r8tr-admin/discount.webp" },
      ],
      createdAt: "2023-11-07T06:48:56.000Z",
      updatedAt: "2023-11-07T06:48:56.000Z",
      projectId: 1,
    },
    Video: {
      id: 5,
      projectVideo: "project-video-1.mp4",
      projectId: 1,
      createdAt: "2023-11-21T05:23:37.000Z",
      updatedAt: "2023-11-21T05:23:37.000Z",
    },
  },
  {
    id: 5,
    projectName: "Template",
    startDate: "12-8-2023",
    endDate: "12-8-2023",
    status: "Completed",
    projectTech: ["React JS", "Redux", "Mui", "Socket", "Firebase"],
    projectDescription:
      "The project involves the creation of a straightforward User Interface (UI) template using the React framework.The UI is enhanced with engaging animations triggered by various user interactions. Specifically, animations have been implemented for on-load events, scroll actions,and hover events. These dynamic animations contribute to a more interactive and visually appealing user experience, enhancing the overall design and usability of the UI template.",
    createdAt: "2023-11-07T06:08:49.000Z",
    updatedAt: "2023-11-07T06:08:49.000Z",
    userName: "arslan_qadir",
    Media: {
      id: 4,
      projectImages: [
        { src: "/images/template/part-1.bmp" },
        { src: "/images/template/part-2.bmp" },
        { src: "/images/template/part-3.bmp" },
        { src: "/images/template/part-4.bmp" },
        { src: "/images/template/part-5.bmp" },
        { src: "/images/template/part-6.bmp" },
      ],
      createdAt: "2023-11-07T06:48:56.000Z",
      updatedAt: "2023-11-07T06:48:56.000Z",
      projectId: 1,
    },
    Video: {
      id: 5,
      projectVideo: "project-video-1.mp4",
      projectId: 1,
      createdAt: "2023-11-21T05:23:37.000Z",
      updatedAt: "2023-11-21T05:23:37.000Z",
    },
  },
  {
    id: 6,
    projectName: "Real Estate",
    startDate: "2-4-2021",
    endDate: "16-7-2021",
    status: "Completed",
    projectTech: ["React JS", "Redux", "Mui", "Socket", "Firebase"],
    projectDescription:
      " The project is a user-friendly online platform for buying and selling properties. Users begin by signing up, enabling them to list their properties for advertisement. Once listed, users can engage with the platform by liking or bookmarking properties of interest. This streamlined process facilitates property transactions and enhances user interaction within the real estate marketplace.",
    createdAt: "2023-11-07T06:08:49.000Z",
    updatedAt: "2023-11-07T06:08:49.000Z",
    userName: "arslan_qadir",
    Media: {
      id: 4,
      projectImages: [
        { src: "/images/real-estate/mainbanner.png" },
        { src: "/images/real-estate/recent-upload.png" },
        { src: "/images/real-estate/popular-residence.png" },
        { src: "/images/real-estate/choose.bmp" },
        { src: "/images/real-estate/tech.bmp" },
        { src: "/images/real-estate/footer.bmp" },
      ],
      createdAt: "2023-11-07T06:48:56.000Z",
      updatedAt: "2023-11-07T06:48:56.000Z",
      projectId: 1,
    },
    Video: {
      id: 5,
      projectVideo: "project-video-1.mp4",
      projectId: 1,
      createdAt: "2023-11-21T05:23:37.000Z",
      updatedAt: "2023-11-21T05:23:37.000Z",
    },
  },
];
