export const skills = [
  {
    id: 1,
    title: "HTML",
    isCoreSkill: true,
    ratePercent: 90,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus esse commodi deserunt vitae, vero quasi! Veniam quaerat tenetur pariatur doloribus.",
    createdAt: "2023-10-31T06:36:59.000Z",
    updatedAt: "2023-10-31T06:36:59.000Z",
    userName: "arslan_qadir",
  },
  {
    id: 2,
    title: "CSS",
    isCoreSkill: true,
    ratePercent: 90,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus esse commodi deserunt vitae, vero quasi! Veniam quaerat tenetur pariatur doloribus.",
    createdAt: "2023-10-31T06:37:07.000Z",
    updatedAt: "2023-10-31T06:37:07.000Z",
    userName: "arslan_qadir",
  },
  {
    id: 3,
    title: "React JS",
    isCoreSkill: true,
    ratePercent: 90,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus esse commodi deserunt vitae, vero quasi! Veniam quaerat tenetur pariatur doloribus.",
    createdAt: "2023-10-31T06:37:27.000Z",
    updatedAt: "2023-10-31T06:37:27.000Z",
    userName: "arslan_qadir",
  },
  {
    id: 4,
    title: "Next JS",
    isCoreSkill: true,
    ratePercent: 90,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus esse commodi deserunt vitae, vero quasi! Veniam quaerat tenetur pariatur doloribus.",
    createdAt: "2023-10-31T06:37:37.000Z",
    updatedAt: "2023-10-31T06:37:37.000Z",
    userName: "arslan_qadir",
  },
  {
    id: 5,
    title: "Node JS",
    isCoreSkill: true,
    ratePercent: 60,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus esse commodi deserunt vitae, vero quasi! Veniam quaerat tenetur pariatur doloribus.",
    createdAt: "2023-10-31T06:37:56.000Z",
    updatedAt: "2023-10-31T06:37:56.000Z",
    userName: "arslan_qadir",
  },
  {
    id: 6,
    title: "JavaScript",
    isCoreSkill: true,
    ratePercent: 90,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus esse commodi deserunt vitae, vero quasi! Veniam quaerat tenetur pariatur doloribus.",
    createdAt: "2023-10-31T06:38:22.000Z",
    updatedAt: "2023-10-31T06:38:22.000Z",
    userName: "arslan_qadir",
  },
  {
    id: 7,
    title: "Material UI",
    isCoreSkill: false,
    ratePercent: 90,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus esse commodi deserunt vitae, vero quasi! Veniam quaerat tenetur pariatur doloribus.",
    createdAt: "2023-10-31T06:38:47.000Z",
    updatedAt: "2023-10-31T06:38:47.000Z",
    userName: "arslan_qadir",
  },
  {
    id: 8,
    title: "And Design",
    isCoreSkill: false,
    ratePercent: 90,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus esse commodi deserunt vitae, vero quasi! Veniam quaerat tenetur pariatur doloribus.",
    createdAt: "2023-10-31T06:39:01.000Z",
    updatedAt: "2023-10-31T06:39:01.000Z",
    userName: "arslan_qadir",
  },
  {
    id: 9,
    title: "Bootstrap",
    isCoreSkill: false,
    ratePercent: 90,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus esse commodi deserunt vitae, vero quasi! Veniam quaerat tenetur pariatur doloribus.",
    createdAt: "2023-10-31T06:39:14.000Z",
    updatedAt: "2023-10-31T06:39:14.000Z",
    userName: "arslan_qadir",
  },
  {
    id: 10,
    title: "Tailwind CSS",
    isCoreSkill: false,
    ratePercent: 90,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus esse commodi deserunt vitae, vero quasi! Veniam quaerat tenetur pariatur doloribus.",
    createdAt: "2023-10-31T06:40:41.000Z",
    updatedAt: "2023-10-31T06:40:41.000Z",
    userName: "arslan_qadir",
  },
  {
    id: 11,
    title: "Mongo DB",
    isCoreSkill: false,
    ratePercent: 90,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus esse commodi deserunt vitae, vero quasi! Veniam quaerat tenetur pariatur doloribus.",
    createdAt: "2023-10-31T06:40:58.000Z",
    updatedAt: "2023-10-31T06:40:58.000Z",
    userName: "arslan_qadir",
  },
  {
    id: 12,
    title: "MySql",
    isCoreSkill: false,
    ratePercent: 90,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus esse commodi deserunt vitae, vero quasi! Veniam quaerat tenetur pariatur doloribus.",
    createdAt: "2023-10-31T06:41:05.000Z",
    updatedAt: "2023-10-31T06:41:05.000Z",
    userName: "arslan_qadir",
  },
  {
    id: 13,
    title: "Docker",
    isCoreSkill: false,
    ratePercent: 90,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus esse commodi deserunt vitae, vero quasi! Veniam quaerat tenetur pariatur doloribus.",
    createdAt: "2023-10-31T06:40:58.000Z",
    updatedAt: "2023-10-31T06:40:58.000Z",
    userName: "arslan_qadir",
  },
  {
    id: 14,
    title: "Git",
    isCoreSkill: false,
    ratePercent: 90,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus esse commodi deserunt vitae, vero quasi! Veniam quaerat tenetur pariatur doloribus.",
    createdAt: "2023-10-31T06:41:05.000Z",
    updatedAt: "2023-10-31T06:41:05.000Z",
    userName: "arslan_qadir",
  },
  {
    id: 15,
    title: "Socket.io",
    isCoreSkill: false,
    ratePercent: 90,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus esse commodi deserunt vitae, vero quasi! Veniam quaerat tenetur pariatur doloribus.",
    createdAt: "2023-10-31T06:40:58.000Z",
    updatedAt: "2023-10-31T06:40:58.000Z",
    userName: "arslan_qadir",
  },
  {
    id: 16,
    title: "Firebase",
    isCoreSkill: false,
    ratePercent: 90,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus esse commodi deserunt vitae, vero quasi! Veniam quaerat tenetur pariatur doloribus.",
    createdAt: "2023-10-31T06:41:05.000Z",
    updatedAt: "2023-10-31T06:41:05.000Z",
    userName: "arslan_qadir",
  },
];
