"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import LeftBar from "@/components/LeftBar/LeftBar";
import TopBar from "@/components/TopBar/TopBar";
import { Box, CssBaseline, Toolbar } from "@mui/material";
import RightBar from "@/components/RightBar/RightBar";
import { ThemeProvider } from "@mui/material/styles";
import { theme } from "@/theme/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const drawerWidth = 280;

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com"  />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <ThemeProvider theme={theme}>
          <Box sx={{ display: "flex", height:"94vh" }}>
            <CssBaseline />
            <TopBar />
            <LeftBar drawerWidth={drawerWidth} />
            <Box
              sx={{
                flexGrow: 1,
                marginLeft: ` ${drawerWidth}px`,
              }}
              className="container"
            >
              <Toolbar />
              {children}
            </Box>
            <RightBar />
          </Box>
        </ThemeProvider>
      </body>
    </html>
  );
}
