import "./globals.css";
import { Box } from "@mui/material";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body suppressHydrationWarning={true}>
        <Box
          sx={{
            padding: {
              xs: "0px 0px",
              sm: "0px 0px",
              md: "0px 40px",
              lg: "0px 40px",
            },
          }}
        >
          {children}
        </Box>
      </body>
    </html>
  );
}
